name: Simple Command
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: echo "Hello, World!"

      - name: Show date
        run: Date
      
      - name: List Files
        run: ls -la